Repository Dzemoro/Project_PT, pull requests merged in 2021-05, with the labels that each got.

#10 Added missing fields to the database and models
  AppDB.db
  AppFunctionsLibrary/Models/Measurement.cs
  SQLQuery/tables.sql
Labels: bug

#20 OnModelCreating override and DB update
  AppDB.db
  AppFunctionsLibrary/Models/AppDatabaseContext.cs
  AppFunctionsLibrary/Models/ConnectorToWire.cs
  AppFunctionsLibrary/Models/WireAttenuation.cs
  SQLQuery/createDB.py
  SQLQuery/fixes.sql
  SQLQuery/print.py
  SQLQuery/tables.sql
Labels: bug, enhancement

#21 backend - WIP
  AppDB.db
  AppFunctionsLibrary/DAL/ChannelRepository.cs
  AppFunctionsLibrary/DAL/ConnectorRepository.cs
  AppFunctionsLibrary/DAL/ConnectorToWireRepository.cs
  AppFunctionsLibrary/DAL/DeviceRepository.cs
  AppFunctionsLibrary/DAL/ObstacleRepository.cs
  AppFunctionsLibrary/DAL/WireAttenuationRepository.cs
  AppFunctionsLibrary/DAL/WireRepository.cs
  AppFunctionsLibrary/Models/AppDatabaseContext.cs
  AppGUI/AppGUI.csproj
  AppGUI/ChannelManager.cs
  AppGUI/ConnectorManager.cs
  AppGUI/ConnectorToWireManager.cs
  AppGUI/DeviceManager.cs
  AppGUI/Form1.Designer.cs
  AppGUI/Form1.cs
  AppGUI/ObstacleManager.cs
  AppGUI/WireAttenuationManager.cs
  AppGUI/WireManager.cs
  SQLQuery/fixes.sql
  SQLQuery/print.py
Labels: enhancement
